apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-service
  namespace: hrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliance-service
      tier: backend
  template:
    metadata:
      labels:
        app: compliance-service
        tier: backend
    spec:
      containers:
      - name: compliance-service
        image: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/compliance-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: "Compliance Service"
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "hrms_compliance_db"
        - name: DB_USER
          value: "hrms_user"
        - name: DB_PASSWORD
          value: "hrms_password"
        - name: AUDIT_SERVICE_URL
          value: "http://audit-service:80/api/v1"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:80/api/v1"
        - name: JWKS_URL
          value: "https://api.asgardeo.io/t/pookieland/oauth2/jwks"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-service
  namespace: hrms
spec:
  selector:
    app: compliance-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006
  type: NodePort
