apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  namespace: hrms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-service
      tier: backend
  template:
    metadata:
      labels:
        app: employee-service
        tier: backend
    spec:
      containers:
      - name: employee-service
        image: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/employee-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: "Employee Management Service"
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "hrms_employees_db"
        - name: DB_USER
          value: "hrms_user"
        - name: DB_PASSWORD
          value: "hrms_password"
        - name: AUDIT_SERVICE_URL
          value: "http://audit-service:80/api/v1"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:80/api/v1"
        - name: COMPLIANCE_SERVICE_URL
          value: "http://compliance-service:80/api/v1"
        - name: JWKS_URL
          value: "https://api.asgardeo.io/t/pookieland/oauth2/jwks"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: hrms
spec:
  selector:
    app: employee-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
