apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: hrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      tier: backend
  template:
    metadata:
      labels:
        app: notification-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
      - name: notification-service
        image: 475936984863.dkr.ecr.ap-southeast-1.amazonaws.com/hrms/notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: "Notification Service"
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "hrms_notifications_db"
        - name: DB_USER
          value: "hrms_user"
        - name: DB_PASSWORD
          value: "hrms_password"
        - name: JWKS_URL
          value: "https://api.asgardeo.io/t/pookieland/oauth2/jwks"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: hrms
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004
  type: NodePort
